name: Negativity
main: com.elikill58.negativity.spigot.SpigotNegativity
version: ${version}
authors: [Elikill58, RedNesto]
description: It's an Advanced AntiCheat Detection, by Elikill58.
api-version: 1.13
softdepend: [ProtocolLib, Essentials, WorldGuard, GadgetsMenu, MaxBans, AdvancedBan, LiteBans, ViaVersion, ProtocolSupport, floodgate, UltraPunishments, Geyser-Spigot]

commands:
  negativity:
    description: See all informations about a player and start verif
    permission: negativity.negativity
    aliases: [neg, n, saltyac, sac]
  nreport:
    description: Report a player
    permission: negativity.report
    aliases: [report, saltyacreport, sacreport]
  nban:
    description: Ban a player
    permission: negativity.ban
    aliases: [ban, saltyacban, sacban]
  nunban:
    description: Unban a player
    permission: negativity.unban
    aliases: [unban, saltyacunban, sacunban]
  nkick:
    description: Kick a player
    permission: negativity.kick
    aliases: [kick, saltyackick, sackick]
  nmod:
    description: Option for mod
    permission: negativity.mod
    aliases: [mod, saltyacmod, sacmod]
  nlang:
    description: Language management
    permission: negativity.lang
    aliases: [lang, saltyaclang, saclang]
  nclearchat:
    description: Clear chat of everyone
    permission: negativity.chat.cleat
    aliases: [clearchat, saltyacclearchat, sacclearchat]
  nlockchat:
    description: Lock chat for not-bypass people
    permission: negativity.chat.lock
    aliases: [lockchat, saltyaclockchat, sacclockchat]
  nwarn:
    description: Warn a player
    permission: negativity.warn
    aliases: [warn, saltyacwarn, sacwarn]

permissions:
  negativity.*:
    description: Gives access to everything.
    children:
      negativity.negativity: true
      negativity.report: true
      negativity.ban: true
      negativity.unban: true
      negativity.kick: true
      negativity.mod: true
      negativity.verif: true
      negativity.alert: true
      negativity.mod: true
      negativity.managecheat: true
      negativity.reportwait: true
      negativity.warn: true
  negativity.negativity:
    description: See all informations about a player and start verif
    default: op
  negativity.report:
    description: Report a player
    default: op
  negativity.ban:
    description: Ban a player
    default: op
  negativity.unban:
    description: Unban a player
    default: op
  negativity.kick:
    description: Kick a player
    default: op
  negativity.mod:
    description: Option for mod
    default: op
